- package.json
> [figma]:update to 1.0.82

- package.json
> [figma]:update to 1.0.94

- package.json
> [figma]:update to 1.0.95

- package.json
> [figma]:update to 1.0.96

- package.json
> [figma]:update to 1.0.97

- package.json
> [figma]:update to 1.0.98

- package.json
> [figma]:update to 1.0.99

- package.json
> [figma]:update to 1.1.13

- package.json
> [figma]:update to 1.1.14

- package.json
> [figma]:update to 1.1.15

- package.json
> [figma]:update to 1.1.17

- package.json
> [figma]:update to 1.1.18

- package.json
> [figma]:update to 1.1.19

- package.json
> [figma]:update to 1.1.23

- package.json
> [figma]:update to 1.1.25

- package.json
> [figma]:update to 1.1.26

- package.json
> [figma]:update to 1.1.27

- package.json
> [figma]:update to 1.1.28

- package.json
> [figma]:update to 1.1.29

- package.json
> [figma]:update to 1.2.4

- package.json
> [figma]:update to 1.3.2

- package.json
> [figma]:update to 1.3.5

- package.json
> [figma]:update to 1.3.11
